- name:  docker image building
  hosts: docker-host
  become: 'yes'
  become_user: devops
  tasks:
       - name: remove all the images
         shell: docker rmi -f $(docker images -q)
       - name: build the docker image
         shell: docker build -f Dockerfile -t medilab-monolith-boot-app-image .
       - name: tag the docker image
         shell: docker tag medilab-monolith-boot-app-image narsi1839/medilab-monolith-boot-app-image
       - name: push the docker image to CR
         shell: docker push narsi1839/medilab-monolith-boot-app-image
